opt_in_rules:

  # performance

  - first_where
  - last_where
  - empty_string
  - empty_count

  # idiomatic

  - legacy_random
  - pattern_matching_keywords
  - redundant_nil_coalescing
  - redundant_type_annotation
  - static_operator
  - toggle_bool
  - joined_default_parameter
  - implicitly_unwrapped_optional
  - convenience_type
  - object_literal
  - force_unwrapping
  - force_cast
  - force_try
  - fatal_error_message
  - extension_access_modifier
  - explicit_init

  # style

  - literal_expression_end_indentation
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - yoda_condition
  - number_separator
  - let_var_whitespace
  - implicit_return
  - conditional_returns_on_newline
  - closure_spacing
  - closure_end_indentation

  # lint

  - private_action
  - private_outlet
  - prohibited_super_call
  - unused_import
  - unused_declaration
  - identical_operands
  - overridden_super_call

excluded:
  - zxcvbn

line_length: 128

cyclomatic_complexity:
  ignores_case_statements: true

type_body_length:
  - 500 # warning
  - 700 # error

file_length:
  warning: 500
  error: 1200

function_parameter_count:
  error: 5

warning_threshold: 1
